// Focused browser regressions for the five shopping upgrades.
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFile} from 'node:fs/promises';
import {resolve,extname} from 'node:path';
import {chromium} from 'playwright';
const root=resolve('docs'),data=JSON.parse(await readFile(resolve(root,'data.json'),'utf8'));
const models=Object.values(data.brands).flatMap(b=>Object.values(b.models));
const all=models.flatMap(m=>m.listings),byVin=new Map(all.map(x=>[x.vin,x]));
const drops=all.filter(x=>{const p=x.series.map(t=>t[1]),distinct=[...new Set(p)];const alternating=distinct.length===2&&p.length>=4&&distinct.every(v=>p.filter(n=>n===v).length>=2)&&p.some((v,i)=>i&&v>p[i-1])&&p.some((v,i)=>i&&v<p[i-1]);return p.length>1&&p.at(-1)<p.at(-2)&&!alternating;});
const server=createServer(async(req,res)=>{const p=resolve(root,'.'+new URL(req.url,'http://local').pathname.replace(/\/$/,'/index.html'));if(!p.startsWith(root+'/'))return res.writeHead(403).end();try{res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.svg':'image/svg+xml'})[extname(p)]||'application/octet-stream');res.end(await readFile(p));}catch{res.writeHead(404).end();}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;
const browser=await chromium.launch();const ctx=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce'});
await ctx.route(/^https?:\/\/(?!127\.0\.0\.1)/,r=>r.abort());
const page=await ctx.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
const dialog=page.locator('.studio-dialog');
try{
 await page.goto(base);await page.locator('#studio-mission').waitFor();
 await page.locator('#studio-mission').selectOption('drops');
 assert.equal(new URL(page.url()).searchParams.get('hunt'),'drops');
 assert.match(await page.locator('.shop-subtitle').textContent(),new RegExp('^'+drops.length+' matching cars'));
 for(const vin of await page.locator('.car-place-card').evaluateAll(ns=>ns.map(n=>n.dataset.carVin)))assert.ok(drops.some(c=>c.vin===vin));
 await page.goBack();assert.equal(await page.locator('#studio-mission').inputValue(),'all');
 await page.getByRole('button',{name:'Monthly',exact:true}).click();
 assert.match(await page.locator('.car-place-price').first().textContent(),/\/mo.*estimated/);
 await page.getByRole('button',{name:'Edit financing',exact:true}).click();
 await page.locator('#shop-apr').fill('0');await page.locator('#shop-apr').press('Tab');
 await page.getByRole('button',{name:'Explore cars',exact:true}).click();
 await page.locator('#studio-monthly-max').fill('1');await page.locator('#studio-monthly-max').press('Tab');
 assert.equal(await page.locator('#map-card').isVisible(),true);
 assert.equal(await page.locator('.car-place-card').count(),0);
 await page.getByRole('button',{name:'Reset search filters',exact:true}).click();
 assert.equal(await page.locator('#studio-monthly-max').inputValue(),'');
 const first=page.locator('.car-place-card').first(),vin=await first.getAttribute('data-car-vin'),row=byVin.get(vin),f=data.buyer.fees;
 const principal=Math.round(row.price*(1+(f.tax_rate||0))+(f.doc_fee||0)+(f.title||0)+(f.registration||0)+(f.ev_surcharge||0)+(f.finance_shipping&&!row.local?(row.ship||0):0));
 const expected=Math.round(principal/data.buyer.finance.default_term);
 assert.ok((await first.locator('.car-place-price').textContent()).includes('$'+expected.toLocaleString('en-US')+'/mo'));
 await first.getByRole('button',{name:'Save car',exact:true}).click();
 assert.equal(await first.getByRole('button',{name:'Saved ✓',exact:true}).getAttribute('aria-pressed'),'true');
 await first.getByRole('button',{name:'Saved ✓',exact:true}).click();
 assert.equal(await first.getByRole('button',{name:'Save car',exact:true}).getAttribute('aria-pressed'),'false');
 await first.getByRole('button',{name:'Quick look',exact:true}).click();
 assert.equal(await dialog.isVisible(),true);
 assert.equal(await page.locator('#studio-title').evaluate(n=>n===document.activeElement),true);
 assert.ok((await dialog.textContent()).includes(vin));
 await dialog.getByRole('combobox',{name:'Status for '+vin}).selectOption('short');
 const note='Ask about battery health <script>window.injected=true</script> and charging cable.';
 await dialog.getByRole('textbox',{name:'Your notes'}).fill(note);
 await dialog.getByRole('button',{name:'← Garage',exact:true}).click();
 assert.equal(await page.locator('#studio-title').evaluate(n=>n===document.activeElement),true);
 await dialog.getByRole('combobox',{name:'Status for '+vin}).selectOption('out');
 assert.equal(await dialog.getByRole('button',{name:'Build dealer brief'}).isDisabled(),true);
 await dialog.getByRole('combobox',{name:'Status for '+vin}).selectOption('called');
 await dialog.getByRole('button',{name:'Build dealer brief'}).click();
 assert.equal(await page.locator('#studio-title').evaluate(n=>n===document.activeElement),true);
 const brief=await dialog.getByRole('textbox',{name:'Dealer brief'}).inputValue();assert.ok(brief.includes(vin)&&brief.includes(note)&&brief.includes(row.url));
 assert.equal(await page.evaluate(()=>window.injected),undefined);
 await page.evaluate(()=>Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:()=>Promise.reject(new Error('denied'))}}));
 await dialog.getByRole('button',{name:'Copy brief',exact:true}).click();
 await page.waitForFunction(()=>document.querySelector('.studio-note-state')?.textContent.includes('Select and copy'));
 await dialog.getByRole('button',{name:'Close',exact:true}).click();
 await page.reload();await page.locator('#studio-mission').waitFor();
 await page.getByRole('button',{name:/^Garage/}).click();assert.ok((await dialog.textContent()).includes(note));
 await dialog.getByRole('button',{name:'Open showroom'}).first().click();
 for(const width of [320,390,820,1440]){await page.setViewportSize({width,height:900});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),width+'px page overflow');assert.ok(await dialog.evaluate(n=>n.scrollWidth<=n.clientWidth+1),width+'px dialog overflow');}
 await dialog.getByRole('button',{name:'Close',exact:true}).click();
 const gone=models.flatMap(m=>m.gone||[]).find(x=>x.last_seen);
 if(gone){await page.evaluate(v=>localStorage.setItem('spicycar.prefs',JSON.stringify({stars:{[v]:'short'}})),gone.vin);await page.reload();await page.locator('#studio-mission').waitFor();await page.getByRole('button',{name:/^Garage/}).click();await dialog.locator('[data-garage-vin="'+gone.vin+'"]').getByRole('button',{name:'Open showroom'}).click();assert.ok((await dialog.textContent()).includes(gone.last_seen));assert.match(await dialog.textContent(),/LEFT THE TRACKED LISTINGS/);}
 assert.deepEqual(errors,[]);
 console.log('studio smoke: radar, exact zero-APR payment, empty recovery, explicit saving, garage statuses, notes persistence, safe briefs, focus, departed records and 320–1440px layouts passed; zero page errors');
}finally{await ctx.close();await browser.close();server.close();}
